"""
Configuration for the World Model based network attack forecasting module.

This module works on top of the trained LSTMEncoder from the LSTM module.

Pipeline:

Traffic sequence
       ↓
Trained LSTM
       ↓
Latent network state
       ↓
World Model
       ↓
Future latent network state
       ↓
Attack probability / risk forecast
"""

import os
import torch


# ============================================================
# PROJECT PATHS
# ============================================================

# Parent project directory
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Existing LSTM module files
LSTM_MODEL_FILE = os.path.join(BASE_DIR, "model.py")
LSTM_CONFIG_FILE = os.path.join(BASE_DIR, "config.py")

# Processed data generated by preprocess.py
PROCESSED_DIR = os.path.join(BASE_DIR, "processed_data")

# LSTM checkpoint generated by train.py
LSTM_CHECKPOINT_PATH = os.path.join(
    BASE_DIR,
    "checkpoints",
    "lstm_model.pth"
)

# Forecasting checkpoints
FORECASTING_CHECKPOINT_DIR = os.path.join(
    BASE_DIR,
    "checkpoints",
    "forecasting"
)

WORLD_MODEL_CHECKPOINT_PATH = os.path.join(
    FORECASTING_CHECKPOINT_DIR,
    "world_model.pth"
)


# ============================================================
# DATA
# ============================================================

X_TRAIN_PATH = os.path.join(
    PROCESSED_DIR,
    "X_train_seq.npy"
)

Y_TRAIN_NEXT_PATH = os.path.join(
    PROCESSED_DIR,
    "y_train_next.npy"
)

X_VAL_PATH = os.path.join(
    PROCESSED_DIR,
    "X_val_seq.npy"
)

Y_VAL_NEXT_PATH = os.path.join(
    PROCESSED_DIR,
    "y_val_next.npy"
)

FEATURE_COLUMNS_PATH = os.path.join(
    PROCESSED_DIR,
    "feature_columns.json"
)

LABEL_ENCODER_PATH = os.path.join(
    PROCESSED_DIR,
    "label_encoder.pkl"
)

SCALER_PATH = os.path.join(
    PROCESSED_DIR,
    "scaler.pkl"
)


# ============================================================
# WORLD MODEL
# ============================================================

# Latent dimension must match LSTM hidden size.
LATENT_SIZE = 256

WORLD_MODEL_HIDDEN_SIZE = 256

WORLD_MODEL_LAYERS = 2

WORLD_MODEL_DROPOUT = 0.2

# Number of future states to generate during forecasting.
FORECAST_STEPS = 3


# ============================================================
# TRAINING
# ============================================================

BATCH_SIZE = 128

EPOCHS = 30

LEARNING_RATE = 1e-4

WEIGHT_DECAY = 1e-5

PATIENCE = 5

GRAD_CLIP_NORM = 5.0

# Weight assigned to latent-state prediction loss.
LATENT_LOSS_WEIGHT = 1.0

# Weight assigned to state-delta prediction loss.
DELTA_LOSS_WEIGHT = 0.25


# ============================================================
# DEVICE
# ============================================================

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


# ============================================================
# FORECASTING
# ============================================================

# Risk levels
LOW_RISK_THRESHOLD = 0.30

MEDIUM_RISK_THRESHOLD = 0.60

HIGH_RISK_THRESHOLD = 0.80


# ============================================================
# CREATE DIRECTORIES
# ============================================================

os.makedirs(
    FORECASTING_CHECKPOINT_DIR,
    exist_ok=True
)