"""
Train the World Model using latent states generated by the trained LSTM.

Run:

    python forecasting/train_world_model.py

Requirements:

    1. preprocess.py must already be executed.
    2. train.py must already be executed.
    3. checkpoints/lstm_model.pth must exist.

The LSTM is frozen during World Model training.
"""

import os
import sys
import json
import time

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader

# ------------------------------------------------------------
# Allow importing model.py from the parent project directory.
# ------------------------------------------------------------

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)


import config
from model import LSTMEncoder

from world_model import WorldModel, world_model_loss
import config_forecasting


# ============================================================
# DATASET
# ============================================================

class WorldModelDataset(Dataset):

    def __init__(self, X_path, y_next_path):

        self.X = np.load(
            X_path,
            mmap_mode="r"
        )

        self.y_next = np.load(
            y_next_path,
            mmap_mode="r"
        )

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):

        current_sequence = torch.tensor(
            np.array(self.X[index]),
            dtype=torch.float32
        )

        next_window = torch.tensor(
            np.array(self.y_next[index]),
            dtype=torch.float32
        )

        # Forecast horizon is normally 1.
        #
        # next_window shape:
        #
        # [forecast_horizon, features]
        #
        next_window = next_window[0]

        return (
            current_sequence,
            next_window
        )


# ============================================================
# LOAD LSTM
# ============================================================

def load_lstm(input_size):

    model = LSTMEncoder(
        input_size=input_size,
        hidden_size=config.HIDDEN_SIZE,
        num_layers=config.NUM_LSTM_LAYERS,
        num_classes=config.NUM_CLASSES,
        dropout=config.DROPOUT,
    ).to(config.DEVICE)

    checkpoint = torch.load(
        config.LSTM_CHECKPOINT_PATH,
        map_location=config.DEVICE
    )

    model.load_state_dict(
        checkpoint["model_state_dict"]
    )

    model.eval()

    # Freeze LSTM parameters.
    for parameter in model.parameters():
        parameter.requires_grad = False

    print("Loaded trained LSTM.")
    print("LSTM parameters frozen.")

    return model


# ============================================================
# CREATE NEXT-SEQUENCE
# ============================================================

def build_next_sequence(
    current_sequence,
    next_window
):
    """
    Convert:

        [x1, x2, ..., xT]

    into:

        [x2, x3, ..., xT, xT+1]

    This represents the network one step in the future.
    """

    next_sequence = torch.cat(
        [
            current_sequence[:, 1:, :],
            next_window.unsqueeze(1)
        ],
        dim=1
    )

    return next_sequence


# ============================================================
# EXTRACT LATENT STATES
# ============================================================

def extract_latent_states(
    lstm,
    current_sequence,
    next_sequence
):
    """
    Generate:

        z_t
        z_(t+1)

    using the frozen LSTM.
    """

    with torch.no_grad():

        current_latent, _, _, _ = lstm(
            current_sequence
        )

        next_latent, _, _, _ = lstm(
            next_sequence
        )

    # We use the final latent representation.
    current_state = current_latent[:, -1, :]

    next_state = next_latent[:, -1, :]

    return (
        current_latent,
        current_state,
        next_state
    )


# ============================================================
# TRAINING
# ============================================================

def train_world_model():

    print("=" * 70)
    print("WORLD MODEL TRAINING")
    print("=" * 70)

    # --------------------------------------------------------
    # Read feature information
    # --------------------------------------------------------

    with open(
        config_forecasting.FEATURE_COLUMNS_PATH
    ) as f:

        feature_columns = json.load(f)

    input_size = len(feature_columns)

    print(
        f"Input feature count: {input_size}"
    )

    # --------------------------------------------------------
    # Dataset
    # --------------------------------------------------------

    train_dataset = WorldModelDataset(
        config_forecasting.X_TRAIN_PATH,
        config_forecasting.Y_TRAIN_NEXT_PATH
    )

    val_dataset = WorldModelDataset(
        config_forecasting.X_VAL_PATH,
        config_forecasting.Y_VAL_NEXT_PATH
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=config_forecasting.BATCH_SIZE,
        shuffle=True,
        num_workers=0,
        pin_memory=False,
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=config_forecasting.BATCH_SIZE,
        shuffle=False,
        num_workers=0,
        pin_memory=False,
    )

    # --------------------------------------------------------
    # LSTM
    # --------------------------------------------------------

    lstm = load_lstm(
        input_size
    )

    # --------------------------------------------------------
    # World Model
    # --------------------------------------------------------

    world_model = WorldModel(
        latent_size=config_forecasting.LATENT_SIZE,
        hidden_size=config_forecasting.WORLD_MODEL_HIDDEN_SIZE,
        num_layers=config_forecasting.WORLD_MODEL_LAYERS,
        dropout=config_forecasting.WORLD_MODEL_DROPOUT,
    ).to(config_forecasting.DEVICE)

    optimizer = torch.optim.AdamW(
        world_model.parameters(),
        lr=config_forecasting.LEARNING_RATE,
        weight_decay=config_forecasting.WEIGHT_DECAY,
    )

    best_val_loss = float("inf")

    epochs_without_improvement = 0

    # ========================================================
    # EPOCH LOOP
    # ========================================================

    for epoch in range(
        config_forecasting.EPOCHS
    ):

        world_model.train()

        start_time = time.time()

        train_total = 0.0
        train_state_loss = 0.0
        train_delta_loss = 0.0

        # ----------------------------------------------------
        # Training
        # ----------------------------------------------------

        for current_sequence, next_window in train_loader:

            current_sequence = current_sequence.to(
                config_forecasting.DEVICE
            )

            next_window = next_window.to(
                config_forecasting.DEVICE
            )

            # Create sequence representing t+1
            next_sequence = build_next_sequence(
                current_sequence,
                next_window
            )

            # Generate latent states
            (
                current_latent_sequence,
                current_state,
                target_state,
            ) = extract_latent_states(
                lstm,
                current_sequence,
                next_sequence
            )

            # Actual latent-state change
            actual_delta = (
                target_state - current_state
            )

            optimizer.zero_grad()

            (
                predicted_state,
                predicted_delta,
                predicted_risk,
                _,
                _,
            ) = world_model(
                current_latent_sequence
            )

            loss, state_loss, delta_loss = world_model_loss(
                predicted_state,
                target_state,
                predicted_delta,
                actual_delta,
                config_forecasting.LATENT_LOSS_WEIGHT,
                config_forecasting.DELTA_LOSS_WEIGHT,
            )

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                world_model.parameters(),
                config_forecasting.GRAD_CLIP_NORM
            )

            optimizer.step()

            train_total += loss.item()
            train_state_loss += state_loss.item()
            train_delta_loss += delta_loss.item()

        train_total /= max(1, len(train_loader))
        train_state_loss /= max(1, len(train_loader))
        train_delta_loss /= max(1, len(train_loader))

        # ----------------------------------------------------
        # Validation
        # ----------------------------------------------------

        world_model.eval()

        val_total = 0.0
        val_state_loss = 0.0
        val_delta_loss = 0.0

        with torch.no_grad():

            for current_sequence, next_window in val_loader:

                current_sequence = current_sequence.to(
                    config_forecasting.DEVICE
                )

                next_window = next_window.to(
                    config_forecasting.DEVICE
                )

                next_sequence = build_next_sequence(
                    current_sequence,
                    next_window
                )

                (
                    current_latent_sequence,
                    current_state,
                    target_state,
                ) = extract_latent_states(
                    lstm,
                    current_sequence,
                    next_sequence
                )

                actual_delta = (
                    target_state - current_state
                )

                (
                    predicted_state,
                    predicted_delta,
                    predicted_risk,
                    _,
                    _,
                ) = world_model(
                    current_latent_sequence
                )

                loss, state_loss, delta_loss = world_model_loss(
                    predicted_state,
                    target_state,
                    predicted_delta,
                    actual_delta,
                    config_forecasting.LATENT_LOSS_WEIGHT,
                    config_forecasting.DELTA_LOSS_WEIGHT,
                )

                val_total += loss.item()
                val_state_loss += state_loss.item()
                val_delta_loss += delta_loss.item()

        val_total /= max(1, len(val_loader))
        val_state_loss /= max(1, len(val_loader))
        val_delta_loss /= max(1, len(val_loader))

        elapsed = time.time() - start_time

        print(
            f"Epoch {epoch + 1}/{config_forecasting.EPOCHS} | "
            f"train_loss={train_total:.6f} | "
            f"train_state={train_state_loss:.6f} | "
            f"train_delta={train_delta_loss:.6f} | "
            f"val_loss={val_total:.6f} | "
            f"val_state={val_state_loss:.6f} | "
            f"val_delta={val_delta_loss:.6f} | "
            f"{elapsed:.1f}s"
        )

        # ----------------------------------------------------
        # Save best model
        # ----------------------------------------------------

        if val_total < best_val_loss:

            best_val_loss = val_total

            epochs_without_improvement = 0

            torch.save(
                {
                    "epoch": epoch,
                    "model_state_dict":
                        world_model.state_dict(),
                    "optimizer_state_dict":
                        optimizer.state_dict(),
                    "val_loss":
                        val_total,
                    "latent_size":
                        config_forecasting.LATENT_SIZE,
                },
                config_forecasting.WORLD_MODEL_CHECKPOINT_PATH
            )

            print(
                "  -> Saved best World Model."
            )

        else:

            epochs_without_improvement += 1

            if (
                epochs_without_improvement
                >= config_forecasting.PATIENCE
            ):

                print(
                    "Early stopping."
                )

                break

    print()
    print("=" * 70)
    print("WORLD MODEL TRAINING COMPLETE")
    print(
        f"Best validation loss: {best_val_loss:.6f}"
    )
    print(
        "Checkpoint:",
        config_forecasting.WORLD_MODEL_CHECKPOINT_PATH
    )
    print("=" * 70)


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":
    train_world_model()